### ISSUE TITLE
parser status (`%_`) disappears as soon as it's drawn

### ISSUE THREAD

**Issue by thetic** [softmoth/zsh-vim-mode#5] opened 2018-07-17 02:28 UTC
`%_` and `%^` become unusable (eg for `PROMPT2` and `RPROMPT2`. They flash briefly before being removed.

**Comment by softmoth** [comment] 2018-07-17 03:21
Hi, thetic, thanks for this report. I'm not able to reproduce it, though. Can you please try with a clean `~/.zshrc`, and report `zsh --version`, so we can narrow down what is causing it?

Here's what I tried. Let me know what you're doing differently.

![shot-20180716](https://user-images.githubusercontent.com/774788/42794784-10e03d0c-893e-11e8-937b-7acc584d0ebd.png)

**Comment by thetic** [comment] 2018-07-17 03:31
I am able to reproduce without my `~/.zshrc` by placing `${MODE_INDICATOR_PROMPT}` in `PS2` or `RPS2`.
![mwe](https://user-images.githubusercontent.com/1388052/42795355-6e12e0dc-8949-11e8-83d6-79f28b74a7c2.png)

**Comment by softmoth** [comment] 2018-07-17 04:02
Ah, I see. I'll look into this, I've never used R/PS2 settings with it and don't take any care to make it work, but it should get fixed.

**Comment by softmoth** [comment] 2018-07-17 08:19
This looks impossible to fix fully (outside of changing zsh, which is probably the right way to go ultimately). The `%_` expansion is the only method for exposing the `cmdstack` values that are kept inside zsh/Src/prompt.c, and the cmdstack is hidden away during line editing. So the only `%_` that's available is whatever is going on inside the zle hooks at the time that `reset-prompt` is called. I.e., if the last time `reset-prompt` was called was inside a for loop and then inside an if, then `%_` will be replaced with `for then`. Which is pretty confusing.

I've pushed a partial fix that at least leaves the `%_` in place if you don't change modes, and just stay in insert mode. Once you hit escape, `%_` will get cleared (or worse, if anybody else is hooking in and calling `reset-prompt`).

Note that this problem happens regardless of whether `${MODE_INDICATOR_PROMPT}` is set in RPS2 or not. I made a typo in my first test, but this problem shows up regardless of that.

I'd appreciate hearing back if this minimizes the problem enough for you to feel that it works as it "should" given the circumstances.

**Comment by thetic** [comment] 2018-07-18 00:50
This change leaves `$VIM_MODE_KEYMAP` empty when the prompt is first generated, which I think is a regression. Can it be defaulted to `viins` or `main`?

**Comment by softmoth** [comment] 2018-07-18 08:00
I think I've fixed that (and a number of other things).

**Comment by softmoth** [comment] 2018-07-19 06:58
Fixed in 734931db

**Closed as completed by softmoth** 2018-07-19 06:58 UTC
Labels: bug, enhancement
