### ISSUE TITLE
This plugin interferes with how HOME and END key works.

### ISSUE THREAD

**Issue by jdhao** [softmoth/zsh-vim-mode#16] opened 2019-10-09 17:14 UTC
I find that this plugin interferes with how HOME and END key works.

# my environment

+ system: macOS
+ terminal: kitty or iterm2

# steps to reproduce

1. use a blank `.zshrc`. Press HOME or END key.  Nothing happens.

2. Add the following line to  `.zshrc` and restart terminal

```
source .zplugin/plugins/softmoth---zsh-vim-mode/zsh-vim-mode.plugin.zsh
```

3. When you press HOME, it will run help on the command currently typed. When you press END key, it will escape the command line to normal mode.

How can I disable this strange behaviour?  With HOME and END doing nothing is better than doing what is appropriate for other key strokes.

**Comment by softmoth** [comment] 2020-04-10 10:37
What does `echo $KEYTIMEOUT` show in your shell when you are seeing this problem? If it is below 30, try removing the setting from your zshrc to see if the problem goes away. This sounds like the shell is timing out before the entire escape sequence is received.

If that's not it, perhaps the escape sequence definition is wrong. You can see the HOME and END key combos by running `cat -v`, and then press HOME and END. It should produce something like `^[[1~` (`<Esc>[1~`). Make sure that those match what is shown in `print $terminfo[khome] $terminfo[kend] | cat -v`. If not , you should fix your terminfo entry for kitty / iTerm2, but you might be able to work around it by adding your escape sequence [around here](https://github.com/softmoth/zsh-vim-mode/blob/master/zsh-vim-mode.plugin.zsh#L55).

I hope this helps.

**Comment by GrzegorzKozub** [comment] 2020-04-23 06:35
Same issue for me only when zsh-vim-mode is loaded. I tested on Gnome Terminal and Alacritty. When I press home in insert or command mode then `run-help` is executed for me. I suspect [this line of code](https://github.com/softmoth/zsh-vim-mode/blob/6b005945d81e85e7aabc173bd082c568244520ab/zsh-vim-mode.plugin.zsh#L161) has something to do with it:
```
vim-mode-bindkey viins       -- run-help                           '^[h'
```
My `cat -v` for the Home key is `^[[H` but `$terminfo[khome]` is `^[OH`. So I was able to work around it by adding this to my `.zshrc`:
```
for MAP in viins vicmd; do
  bindkey -M $MAP "^[[H" beginning-of-line
  bindkey -M $MAP "^[[F" end-of-line
done
```

**Comment by softmoth** [comment] 2020-04-23 17:36
Thank you, Grzegorz. I wouldn't be surprised if you've also got a mismatch for other characters. I'd love to be able to document a real fix -- that is, identifying why your terminfo content doesn't match your terminal -- if this is a common problem people run into. You could check these to ensure they match:

    # Arrow keys: Left, Right, Up, Down
    for k in kcub1 kcuf1 kcuu1 kcud1; do print "$k\t$terminfo[$k]"; done | cat -v
    # PgUp, PgDown, Home, End, Insert, Delete, Shift-Tab
    for k in kpp knp khome kend kich1 kdch1 kcbt; do print "$k\t$terminfo[$k]"; done | cat -v

You can add your terminal's escape sequence [at the end of the special key definition](https://github.com/softmoth/zsh-vim-mode/blob/6b005945d81e85e7aabc173bd082c568244520ab/zsh-vim-mode.plugin.zsh#L47-L59). For example:

    vim-mode-define-special-key Home       khome "^[[1~" "^[[H"
    vim-mode-define-special-key End        kend  "^[[4~" "^[[F"

But ideally, you'd look at your `$TERM` variable, check the documentation for Gnome Terminal and Alacritty and ensure you've got all packages in sync. For example, it looks like ncurses 6.1 includes alacritty terminfo  definitions, and you'd want to have the latest ncurses package and `TERM=alacritty` set (it should be the default). Gnome Terminal obviously should be well supported by the OS, so I expect there's something in your setup that is overwriting your `TERM`.

If you're using `screen` or `tmux`, you've got another layer of indirection to care about. You should have `TERM` set properly before running tmux, and then set `TERM=screen-256color` inside.

I hope this is helpful. If any of this works, let me know and I can update the README with some tips for other users.

**Comment by softmoth** [comment] 2020-05-02 18:57
I've removed a few bindings that [begin with `<Escape>`](https://github.com/softmoth/zsh-vim-mode/commit/6d95b96fe20a8c0d5eb939c8b20c6191666d3ec7). A nice side-effect for you is that HOME will no longer cause `run-help` to fire. However, I would still love to identify why your HOME/END keys are not mapping to the Home and End behaviors like they should! If this is a problem that lots of people have with zsh-vim-mode, I'd really like to be able to document a solution.

Thanks for any further info you can provide. In the mean time, you may want to pull an updated copy of this repo to see if it's more pleasant for you to use.

**Comment by GrzegorzKozub** [comment] 2020-05-03 08:52
Since my behavior is the same for Gnome Terminal and Alacritty I will focus on Alacritty. I removed my workaround and unloaded `zsh-vim-mode` and then run your checks:
```
for k in kpp knp khome kend kich1 kdch1 kcbt; do print "$k\t$terminfo[$k]"; done | cat -v
kpp	^[[5~
knp	^[[6~
khome	^[OH
kend	^[OF
kich1	^[[2~
kdch1	^[[3~
kcbt	^[[Z
> cat -v
^[[5~ ^[[6~ ^[[H ^[[F ^[[2~ ^[[3~ ^[[Z ^C
> for k in kcub1 kcuf1 kcuu1 kcud1; do print "$k\t$terminfo[$k]"; done | cat -v
kcub1	^[OD
kcuf1	^[OC
kcuu1	^[OA
kcud1	^[OB
> cat -v
^[[D ^[[C ^[[A ^[[B ^C
> echo $TERM
xterm-256color
```
Does this output mean I have differences for Home, End and arrow keys? My `$TERM` variable seems set by Alacritty itself and I don't run tmux in this case.
Interestingly, when I updated `zsh-vim-mode` to include the fix you mentioned I still have the same problem. Not sure I'm debugging this correctly, but:
```
bindkey | grep run-help
"^[h" run-help
```

**Comment by softmoth** [comment] 2020-05-04 19:52
Grzegorz (and jdhao for the initial report!),

Thanks so much for digging into this. I have a few updates:

1. It is my mistake that `^[h` is still bound; I reversed the [logic of the test](https://github.com/softmoth/zsh-vim-mode/commit/6d95b96fe20a8c0d5eb939c8b20c6191666d3ec7#diff-15f06e2f39bde2c4438207ef4113fa54R140); it _should_ read `if (( $+VIM_MODE_VICMD_KEY ))`.

2. I have been able to repeat this with Alacritty if I remove my `~/.config/alacritty/alacritty.yml` config file. I checked the supplied `/usr/share/doc/alacritty/example/alacritty.yml`, and it doesn't include the key bindings that used to be there. BUT from the bindings in my old config that made me not notice this issue, it appears the problem is with Application mode. I've [opened another issue](https://github.com/softmoth/zsh-vim-mode/issues/22) for the bigger problem.

3. Since I can repeat it, I've [committed a workaround](https://github.com/softmoth/zsh-vim-mode/commit/4848dd324f2467007eb1cdf2801f5c28293ad38b) for the problem and will close this issue. Feel free to re-open it if your HOME/END keys are still not working with the latest code!

**Closed as completed** 2020-05-04 19:52 UTC

**Comment by jdhao** [comment] 2020-05-05 04:51
Sorry for the late reply. The latest update works. Now I do not need to set up bindkey hacks for HOME and END to work.

**Comment by GrzegorzKozub** [comment] 2020-05-06 18:01
Works great now, thank you!
